### ISSUE TITLE
HTML entities: Already escaped characters are turned into entities

### ISSUE THREAD

**Issue by WilliamHolmes** [punkave/sanitize-html#103]
I can't seem to find a flag to set to ensure entities are not returned.
ie.  Currently 
```
sanitizeHTML("\"hello<br/>world\"", {allowedTags: [], parser: {decodeEntities: true}})
```
returns
```
"&quot;helloworld&quot;"
```
But I was expecting...
```
"\"helloworld\""
```
I have also tried {decodeEntities: false} just incase I'm misinterpreting something.

**Comment by boutell** [comment]
The current escaping is valid HTML and has the right result in the browser, etc. Options to not correctly escape things will not be happening. Pull requests to not escape things in contexts where those things are valid not to escape may be accepted, though.
