### ISSUE TITLE
Empty attributes

### ISSUE THREAD

**Issue by juanjardim** [punkave/sanitize-html#123]
Hi, I notice after doing a transformation the empty attributes are not valid any more Example of the src element in an image tag
**Before**
`<img src="" style="-ms-interpolation-mode:bicubic;clear:both;display:block;max-width:100%;outline:0;text-decoration:none;width:auto">`
**After**
`<img src style="-ms-interpolation-mode:bicubic;clear:both;display:block;max-width:100%;outline:0;text-decoration:none;width:auto"/>`

Not sure if it is a bug, but can you help me?

**Comment by boutell** [comment]
Empty attributes without "" are valid according to the standards and accepted by all browsers.

**Comment by dylanarmstrong** [comment]
Not to reopen the issue, but they're not accepted in EPUB3.3 and iBooks will throw up a nasty error if you try and load something like: `<img src='image.jpg' width />`.

Here's a solution if anyone else comes across this using `transformTags`:

```
sanitizeHtml(dirty, {
  transformTags: {
    '*': function (tagName, attribs) {
      const cleanAttribs = { ...attribs };

      Object.keys(cleanAttribs).forEach((key) => {
        const value = String(cleanAttribs[key]).trim();
        if (value === '') {
          delete cleanAttribs[key];
        }
      });

      return {
        attribs: cleanAttribs,
        tagName,
      };
    },
  },
};
```

**Comment by boutell** [comment]
The HTML spec contains "boolean attributes," like `checked`, that *should not* have an explicit value. Their presence implies that they are active:

https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes

So removing these could do more harm than good, even at project level.

On the other hand, a PR to remove specific empty attributes that are known to be (1) of no value anywhere and (2) problematic in some contexts would be welcome (e.g. purging `src` if it is empty).

**Comment by dylanarmstrong** [comment]
You're right, it is valid HTML, but in my instance, I'm using this tool to sanitize HTML before putting it into EPUB XHTML documents. You can't have boolean attributes in EPUB XHTML documents per: https://www.w3.org/TR/2002/REC-xhtml1-20020801/#h-4.5 .

So for me, removing them is fine. There aren't any elements that have boolean attributes that I want displaying on my Kindle in a book. A checked input field isn't exactly useful there :) I was just posting the code, in case someone else came across this same issue.

Although, I think a PR to check if an attribute is boolean and remove non-boolean empty attributes would be nice. I can try and work on this this week actually, if you think that'd be a good fit for the project. There's only 24 attributes that are boolean: https://html.spec.whatwg.org/multipage/indices.html#attributes-3

Thoughts?

**Comment by dylanarmstrong** [comment]
Sounds good, and yes thank you for this project, it's very helpful!
