### ISSUE TITLE
Ignore (not exclude) arbitrary text that is wrapped in <> ?

### ISSUE THREAD

**Issue by kwhitaker** [punkave/sanitize-html#126]
I need to be able to sanitize text that has a subset of html tags (`b, i, br`), but may _also_ include active-directory style email addresses, such as `<outlook.address@domain.com>` or `</o=some-string /ou=some-other-string >`

Is there any way I can set sanitize to ignore those weird addresses/strings?

Thanks

**Comment by boutell** [comment]
Sorry, we will not be adding support for anything htmlparser2 won't parse (very tolerantly) as HTML.
