### ISSUE TITLE
Is there a way to make the tags displayed without executing them , like <script> to &lt;script&gt; 

### ISSUE THREAD

**Issue by Jeyanthinath** [punkave/sanitize-html#142]
I searched over the documentation and other websites . I can't really come up with solution to make the things displayed in a html way

I am creating a project with WYSIWYG editor , there we can insert code , I want to display the code to the html page without stripping it out , but here I can't able to.

I need <script> to ``&lt;script&gt;``

**Comment by boutell** [comment]
This isn't sanitization, it's not really in scope.
