### ISSUE TITLE
sanitize-html is stripping src attributes from images when using data URLs

### ISSUE THREAD

**Issue by george-norris-salesforce** [punkave/sanitize-html#144]
**[Here is an example](https://runkit.com/george-norris-salesforce/58d4c1cacacafe0014733f92)**

const htmlStr = `<p><img class="fr-dib fr-fil" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKoAAABWCAYAAABfJg3gAAABtElEQVR4Ae3SUQ3AIBAFQeCrmrBT/xpKUhVsMqfgZW/ms99vOAUuL7Au32eeAn8BUEFIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjASVgUQBUBNvMhJUBhIFQE28yUhQGUgUADXxJiNBZSBRANTEm4wElYFEAVATbzISVAYSBUBNvMlIUBlIFAA18SYjQWUgUQDUxJuMBJWBRAFQE28yElQGEgVATbzJSFAZSBQANfEmI0FlIFEA1MSbjDwpDAJQoPPD7AAAAABJRU5ErkJggg==" style="width: 300px;"></p>`;
```
sanitizeHTML(htmlStr, {
          allowedTags: ['img'],
          allowedAttributes: {
            img: ['src', 'align']
          }
        });
```

outputs...
`<img />`

[![https://gyazo.com/b89f016f464fd9e75a5c40ca5cf392d2](https://i.gyazo.com/b89f016f464fd9e75a5c40ca5cf392d2.gif)](https://gyazo.com/b89f016f464fd9e75a5c40ca5cf392d2)

using latest version

**Comment by george-norris-salesforce** [comment]
ahh needed to change the scheme 🤔

**Comment by bestwestern** [comment]
What was the solution exactly? 
I have the same problem 😕

**Comment by Lazer7** [comment]
Hi, I just wanted to provide more context for the solution provided by boutell to any lost traveler that stumbles upon this thread. The `<img>` tag will still get the src stripped if you do not provided the allowedSchemes into the options when you use sanitizeHtml. To allow src to include http, https or in the above issue dataURI in the source of an image you will need to specify those values in the allowedSchemes.

Example: 
```
sanitizeHtml(htmlStr, {
     allowedTags: sanitizeHtml.defaults.allowedTags.concat([ 'img' ]),
     allowedAttributes: {'img': ['src']},
     allowedSchemes: [ 'data', 'http', 'https']
});
```
To find more information about the issue: https://github.com/apostrophecms/sanitize-html#allowed-url-schemes

**Comment by boutell** [comment]
Thanks for clarifying!
