### ISSUE TITLE
Add dist folder with minified version for every release tag

### ISSUE THREAD

**Issue by mloayzagahona** [punkave/sanitize-html#146]

**Comment by simison** [comment]
https://github.com/bower/bower/issues/368

**Comment by breck7** [comment]
I believe adding this is as simple as using the "files" property in the package.json.

**Comment by breck7** [comment]
```

{
  "name": "sanitize-html",
"files": ["dist"... ]
...
}
```

**Comment by boutell** [comment]
Resolved in 1.16.3 I believe, if not feel free to PR whatever minor changes are needed.
