### ISSUE TITLE
No Dist folder

### ISSUE THREAD

**Issue by aveshnaik007** [punkave/sanitize-html#153]
"You'll find the minified and unminified versions of sanitize-html (with all its dependencies included) in the dist/ directory."

    <html>
      <body>
          <script type="text/javascript"  src="dist/sanitize-html.js"></script>
          <script type="text/javascript" src="demo.js"></script>
      </body>
     </html>
Where is Dist folder ?? it is not include

**Comment by simison** [comment]
You can build those yourself:

`npm install && npm run build``

**Comment by styfle** [comment]
@simison Any reason why dist is not committed and published to npm?

There are tools like unpkg.com that make it really easy for front-end devs to avoid build tools.

For example, include this the following url to get started with React.js: https://unpkg.com/react@15.6.1/dist/react.min.js

It's ready the code straight from npm.

**Comment by boutell** [comment]
This is documented in the README, it's indicated there what steps you have to run to create the dist/ folder. Browser-side use is a secondary application, there are not many use cases where it makes more sense than server-side.
