### ISSUE TITLE
Version 1.14.2 fails to load needed dependency.

### ISSUE THREAD

**Issue by AccaliaDeElementia** [punkave/sanitize-html#173]
Discovered by our travis builds triggered by greenkeeper, with version 1.14.2 a clean install fails to find module `lodash.escaperegexp` when using this module

it appears the change to package.json for [this commit](https://github.com/punkave/sanitize-html/commit/b7d71de6985a272ab66ec264b56bd5b202e2c3b0) which introduced the dependency on lodash.escaperegexp was recently reverted by [this commit](https://github.com/punkave/sanitize-html/commit/77e36193fd3ce8e323dc7d093ad323108fdba387), possibly in error.

Relevant excerpt from the build log follows:
```
Error: Cannot find module 'lodash.escaperegexp'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/SockDrawer/SockBot/node_modules/sanitize-html/index.js:3:19)
```

Complete build log can be found [here](https://travis-ci.org/SockDrawer/SockBot/jobs/294905919) if additional information is needed

**Comment by boutell** [comment]
Fixed, sorry for the hassle.
