### ISSUE TITLE
SCRIPT1002: Syntax error In IE 10

### ISSUE THREAD

**Issue by Wobbly-Wibbly** [punkave/sanitize-html#194]
SCRIPT1002: Syntax error
I belive it's line 45 in npm module index.js

`const VALID_HTML_ATTRIBUTE_NAME = /^[^\0\t\n\f\r /<=>]+$/;`

![image](https://user-images.githubusercontent.com/2401271/34357022-ea407996-ea4b-11e7-968f-77918e3ec2c6.png)

In 1.14.1 it's ok

**Comment by boutell** [comment]
Per the documentation, please use the babel-compiled version in the dist/ folder.
