### ISSUE TITLE
Option to disable html escaping?

### ISSUE THREAD

**Issue by RandomSeeded** [punkave/sanitize-html#211]
Hi,

This may be a bit of an unusual use-case, but I was hoping to use this library to both sanitize user-provided HTML and also be able to tell the user when they've provided invalid / disallowed HTML. The best approach I've thought of was to check to see if the sanitized html was equivalent to the original html and error if they differ, but this fails due to the sanitization in `escapeHtml`.

Would you be amenable to a PR with an option to disable `escapeHtml`? Alternately, is there a cleaner approach to my goal that I'm missing?

Appreciate it

**Comment by boutell** [comment]
htmlparser2 doesn't provide a way to get the original representation while also sanitizing safely, so this is out of scope for this module.

**Comment by RandomSeeded** [comment]
For anybody who may run across this in the future; got the result I needed by sanitizing twice, once with normal options and once with `allowedTags: false` and `allowedAttributes: false` and diffing
