### ISSUE TITLE
How to set or override target= “_blank” in anchor tag in 'sanitize-html' ?

### ISSUE THREAD

**Issue by akhilaudable** [punkave/sanitize-html#223]
I asked the same question here as well : https://stackoverflow.com/questions/50286819/how-to-set-or-override-target-blank-in-anchor-tag-in-sanitize-html

And I ask the question again here. 

I am using sanitize-html in my project. Say suppose I get a mail which has anchor tag, something like this:
```
this is to test something <a href="https://www.google.com/">open google</a>
```
This mail appears in my mail box like this :
```
this is to test something open google
```

Which opens google.com in the same tab. **But I need to open in new tab.**
Here is my code.
```
__html = sanitizeHTML(children, {
        allowedTags: sanitizeHTML.defaults.allowedTags.concat([ 'img' ]),
        allowedAttributes: {
          '*': [ 'href', 'align', 'alt', 'center', 'bgcolor', 'style', 'width' ],
          'img': ['src'],
          'a' : ['target'] 
        },
       }

```

Here I want to **set or override** target = "_blank" . How to achieve that in sanitize-html ?

Unfortunately I could not find a tag for sanitize-html in stackoverflow.

**Comment by boutell** [comment]
Looks like someone subsequently answered this question for you on SO.
