### ISSUE TITLE
Allow a way to keep relative url for iFrame src attribute?

### ISSUE THREAD

**Issue by parthdesai93** [punkave/sanitize-html#239]
Currently, there is no way to preserve relative url's when it comes to iframe's src attribute. Is there a particular reason for it? Is it possible for us to pass an option with which we can keep the relative url instead of appending `https:`?

[This](https://github.com/punkave/sanitize-html/blob/master/src/index.js#L245) is the line in the code which specifically checks for tag to be `iframe` and attribute to be `src` and appends `https:` to `//`.

**Comment by boutell** [comment]
Fix merged, publishing. Thanks.
