### ISSUE TITLE
Cannot pass parser options when using typescript

### ISSUE THREAD

**Issue by WillGibson** [punkave/sanitize-html#248]
e.g.

```
return sanitizeHtml(
    text,
    {
        parser: {
            decodeEntities: false
        }
    }
);
```

Simple fix which I've tested locally, PR coming in some minutes, just creating the issue to link it all together.

**Comment by WillGibson** [comment]
The PR is here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28502

**Comment by boutell** [comment]
I'm not a typescripter but... LGTM! I assume you've tested this with typescript and all is well.

**Comment by WillGibson** [comment]
Yes. I had to make the change locally to test, then did the PR

**Comment by sirMerr** [comment]
Hey @WillGibson , I'm using the updated type definition, but this makes it so that `parser` is mandatory when I believe it should be optional.

I've opened a PR here real fast, although I'm at work so can't test it until later ^^: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28653

**Comment by boutell** [comment]
Parser is definitely optional in the original module.

**Comment by WillGibson** [comment]
NOw @sirMerr's PR is merged, I've made one to update the tests to cover it boths ways...

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28682
