### ISSUE TITLE
How to remove tag with specified style value?

### ISSUE THREAD

**Issue by Kuvalda** [punkave/sanitize-html#254]
I want to remove (or replace) tags with specified value of style i.e. position:fixed.

As described in doc i think use 

```
transformTags: {
          '*': (tagName, attribs) => {
              console.log('[TAG]', tagName, attribs)
              return {
                  tagName,
                  attribs
              };
          }
        }

```

But i see in attribs that style attribute not parsed to values and it original string.
And i'm not sure can i remove tag and its content by return nothing or empty object?

**Comment by boutell** [comment]
This is out of scope for this module. I would use `cheerio` for a more complex use case like this.

**Comment by boutell** [comment]
However if it is good enough for you you could use the allowedStyles option to just clean up the elements rather than removing them entirely.

**Comment by Kuvalda** [comment]
@boutell , thanx for attention!

**cheerio** is not enought for me because i use vue.js on front and node.js on back and don't need for direct DOM manipulation.

Now, i try use **sanitize** for cleanup html with strong rules in my project at both ends.
