### ISSUE TITLE
Wrong URL encoding

### ISSUE THREAD

**Issue by Kikobeats** [punkave/sanitize-html#274]
Hello,

I noted the library is wrongly encoding the following URL:

```
https://o.aolcdn.com/images/dims?thumbnail=1200%2C630&quality=80&image_uri=https%3A%2F%2Fo.aolcdn.com%2Fimages%2Fdims%3Fcrop%3D4834%252C3230%252C0%252C0%26quality%3D85%26format%3Djpg%26resize%3D1600%252C1069%26image_uri%3Dhttps%253A%252F%252Fs.yimg.com%252Fos%252Fcreatr-images%252F2019-01%252F2d1e22f0-12ae-11e9-bae7-60d640081814%26client%3Da1acac3e1b3290917d92%26signature%3D269ae0af3a1a1772ffea6759d126791b9ad25184&client=amp-blogside-v2&signature=ea8c3bcfcab1cb450830a18333e5a76988365326
````

Specifically, the library is doing unreacheable the URL converting `&image;` into `ℑ`.

Sample code for reproducing that:

```js
'use strict'

const sanitizeHtml = require('sanitize-html')

const sanitize = html =>
  sanitizeHtml(html, {
    allowedTags: false, // allow all tags
    allowedAttributes: false, // allow all attributes
    parser: {
      lowerCaseTags: true,
      decodeEntities: true,
      lowerCaseAttributeNames: true
    }
  })

const html = sanitize(`
<html lang="en">
<meta property="og:image" content="https://o.aolcdn.com/images/dims?thumbnail=1200%2C630&quality=80&image_uri=https%3A%2F%2Fo.aolcdn.com%2Fimages%2Fdims%3Fcrop%3D4834%252C3230%252C0%252C0%26quality%3D85%26format%3Djpg%26resize%3D1600%252C1069%26image_uri%3Dhttps%253A%252F%252Fs.yimg.com%252Fos%252Fcreatr-images%252F2019-01%252F2d1e22f0-12ae-11e9-bae7-60d640081814%26client%3Da1acac3e1b3290917d92%26signature%3D269ae0af3a1a1772ffea6759d126791b9ad25184&client=amp-blogside-v2&signature=ea8c3bcfcab1cb450830a18333e5a76988365326">
</html>
`)

console.log(html)
```

I'm not suring why this happening 🤔

**Comment by boutell** [comment]
When they appear as part of an HTML attribute, `&` symbols must be correctly escaped as `&amp;`. Your input does not do this, so while the parser follows various "try and make sense of it" rules in the absence of the escaping, it is vulnerable to misinterpretation if the characters following the `&` resemble a known HTML entity escape code. This is not a bug in sanitize-html or htmlparser2, your input must be well-formed.

**Comment by Kikobeats** [comment]
Although I agree with you, that's an assumption difficult to accomplish when you are handling an arbitrary HTML markup and I expected that as part of the library responsibility

**Comment by boutell** [comment]
And it does what you're asking, except when the markup is actually ambiguous and it really can't tell what you want, as in this case (:
