### ISSUE TITLE
Problem during npm install - npm ERR! Unexpected end of JSON input while parsing near '...Bwl4pqeBsuk8lobbm\nFv'

### ISSUE THREAD

**Issue by ismaelkedir** [punkave/sanitize-html#279]
I tried installing the package from npm using the command:
**$** npm i sanitize-html
...And this appeared after a second...
**npm ERR!** Unexpected end of JSON input while parsing near '...Bwl4pqeBsuk8lobbm\nFv'

**Comment by boutell** [comment]
Just did a successful test install. If you are having `npm install` problems that likely has to do with your install of node and npm and is unrelated to this module.
