### ISSUE TITLE
Sanitize text nodes

### ISSUE THREAD

**Issue by brianreavis** [punkave/sanitize-html#28]
This might be out of the scope of this module, but I was wondering if there are any plans to add support for custom processing of text within HTML. If not, would this be a welcomed feature? Use cases:
- Cleaning sloppy text formatting: `---` vs `–`, `--` vs `–`, etc. Perhaps [typogr](https://github.com/ekalinin/typogr.js) / [tipograph](https://www.npmjs.org/package/tipograph) are better for this.
- Filtering out profanity if that's your thing.
```js
sanitizeHtml(html, {
	textFilter: function(text) {
		return text
			.replace(/\s?\-\-\-\s?/, '&mdash;')
			.replace(/\s?\-\-\s?/, '&ndash;')
			.replace(/\s?\.\.\.?/, '&hellip;');
	}
});
```
Thanks!

**Comment by csabapalfi** [comment]
Done.
