### ISSUE TITLE
Produces invalid HTML5

### ISSUE THREAD

**Issue by bard** [punkave/sanitize-html#282]
Test case:

```js
const sanitizeHtml = require('sanitize-html')
const html = '<p><img src="foo.jpg"> hello, world</p>'
const sanitized = sanitizeHtml(html, { allowedTags: ['img', 'p'] })
console.log(sanitized)
```

Prints:

```html
<p><img src="foo.jpg" /> hello, world</p>
```

Expected:

```html
<p><img src="foo.jpg"> hello, world</p>
```

Reference: 

> Void elements:
area, base, br, col, embed, hr, img, input, link, meta, param, source, track, wbr (https://www.w3.org/TR/html5/syntax.html#writing-html-documents-elements)

> Void elements only have a start tag; end tags must not be specified for void elements. (https://www.w3.org/TR/html5/syntax.html#void-elements)

The obvious fix would be at https://github.com/punkave/sanitize-html/blob/master/src/index.js#L326:

```diff
        if (options.selfClosing.indexOf(name) !== -1) {
-         result += " />";
+         result += ">";
        } else {
```

I can prepare a PR if that's a good way to fix this.

**Comment by boutell** [comment]
That's not what "end tag" means:

https://www.w3.org/TR/html5/syntax.html#end-tags

The spec is saying you can't have `</img>`. Not that you can't have `<img ... />`.

**Comment by bard** [comment]
That's right, I should have checked the validator first. Apologies for the noise.
