### ISSUE TITLE
Can parsing tags be parallel?

### ISSUE THREAD

**Issue by MrLeeGit** [punkave/sanitize-html#284]
for example：
```
<p>I am the most handsome.<p>I'm kind, too.</p>everyone likes me very much.</p>
```
result：
```
<p>I am the most handsome.</p>
<p>I'm kind, too.</p>
<p>everyone likes me very much.</p>
```
sanitize-html error show:

```
<p>I am the most handsome.</p><p>I'm kind, too.</p>everyone likes me very much.<p></p>

```

**Comment by boutell** [comment]
This is a correct parsing of the document, which does not close p tags properly; the auto-closing kicks in when the second p tag shows up, and the third clearly starts outside of any p tag. Then a stray closing p shows up, and outputting `<p></p>` in response is a little odd I guess, but it's not invalid, while the original markup is invalid, so...

🤷‍♂️
