### ISSUE TITLE
regression from 1.4.3 to 1.5.1

### ISSUE THREAD

**Issue by zeke** [punkave/sanitize-html#39]
After upgrading to 1.5.1, I began seeing the following error in tests that used to pass:

```
TypeError: Uncaught error: Cannot call method 'test' of undefined
    at /Users/z/n/newww/node_modules/marky-markdown/node_modules/sanitize-html/index.js:132:46
```

I worked around it by adding `span: []` to the `allowedAttributes` map:

https://github.com/npm/marky-markdown/blob/f6c7dbc6c6d2d583badde66c4982481d9f8ab435/lib/sanitize.js#L49

I think there needs be a check to ensure `allowedAttributesGlobMap[name]` is a string before calling `test()`.

Thanks for creating this package, by the way. It's got a nice intuitive API. We're now using it on https://www.npmjs.com/ to sanitize READMEs.

**Comment by boutell** [comment]
Good catch, this is fixed. Glad you're finding it useful on npmjs.com!
