### ISSUE TITLE
On stripping "undefined"

### ISSUE THREAD

**Issue by eush77** [punkave/sanitize-html#44]
[These lines](https://github.com/punkave/sanitize-html/blob/9c6dcc812fb1d176c16611b94a2def47668ffc42/index.js#L222-L224) seem to explicitly disallow `"undefined"` as an HTML content.

```js
> sanitizeHtml('undefined')
''
> sanitizeHtml('undefined-whatever')
'undefined-whatever'
```

This behavior is causing issues downstream: npm/marky-markdown#26
What is the reason for this?

**Comment by boutell** [comment]
How strange. git blame says it was me! My best guess is I was working around an early bug in Apostrophe which is no longer relevant. The test suite passes without this code, so I've removed it and published 1.6.1. Thanks for the report.
