### ISSUE TITLE
transformTags and edit textContent

### ISSUE THREAD

**Issue by sradu** [punkave/sanitize-html#45]
I'm trying to transform links like:
```
<a href='http://url.com'>check this out</a>
```
to 
```
<span>check this out [http://url.com]</span>
```

transformTags looks like the option for me, however there's no way to edit the text. attribs does not contain the textContent.

Any ideas how I could implement this?

**Comment by boutell** [comment]
I think you might be happier with something like cheerio for a task like
that.

cheerio is an implementation of jquery based on htmlparser2, for use in
manipulating markup on the server side. It can do all that jazz, it's just
a little more heavyweight than sanitize-html.

Or you could use htmlparser2 directly yourself.

On Wed, Feb 25, 2015 at 2:15 PM, Radu Spineanu <notifications@github.com>
wrote:

> I'm trying to transform links like:
>
> check this out <http://url.com>
> to
> check this out [http://url.com]
>
> transformTags looks like the option for me, however there's no way to edit
> the text. attribs does not contain the textContent.
>
> Any ideas how I could implement this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/45>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by sradu** [comment]
I could, but I love sanitize-html for it's simplicity, and I'm so close to having it work. This would be the only thing.

**Comment by boutell** [comment]
Thing is, as soon as we have this feature, the logical question is what to
do with nested tags. And their text. And their nested tags.

And the logical answer is to build a structure of the whole shebang. But,
at that point we're using more resources and time and creeping toward
something more like Cheerio anyway (:

On Wed, Feb 25, 2015 at 3:08 PM, Radu Spineanu <notifications@github.com>
wrote:

> I could, but I love sanitize-html for it's simplicity, and I'm so close to
> having it work. This would be the only thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/45#issuecomment-76045146>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by sradu** [comment]
OK :(

**Comment by ile** [comment]
Why couldn't there be a third argument for the transformTags callback:

`options.transformTags.a = (tagName, attribs, text) ->`

?
