### ISSUE TITLE
Add possibility for custom HTML entities ecaping

### ISSUE THREAD

**Issue by pavlo-yuriychuk** [punkave/sanitize-html#48]
Right now your library provides pretty straightforward transformation:

~~~javascript
  function escapeHtml(s) {
    if (typeof(s) !== 'string') {
      s = s + '';
    }
    return s.replace(/\&/g, '&amp;').replace(/</g, '&lt;').replace(/\>/g, '&gt;').replace(/\"/g, '&quot;');
  }
~~~

But other libs have more powerful escaping capabilities, see https://www.npmjs.com/package/html-entities.

Would be great to have `escapeHtmlEntities` parameter that is defaulted by your internal escape function and can be customized.

~~~javascript
var Entities = require('html-entities').AllHtmlEntities;
entities = new Entities();

clean = sanitizeHtml(dirty, {
  allowedTags: [ 'b', 'i', 'em', 'strong', 'a' ],
  allowedAttributes: {
    'a': [ 'href' ]
  },
 escapeHtmlEntities: function (text) {
    return entities.encode(text);
 }
});
~~~

**Comment by boutell** [comment]
Why would you want to do this, though? The characters I'm escaping are the only ones that would break the markup. Everything else is less verbose and more readable left as-is.

**Comment by pavlo-yuriychuk** [comment]
@boutell : I wanted to do that just to do more advanced handling of Html text inside links. It is required in our project to escape almost all special characters. You may treat this feature as just nice to have, but IMHO it is essential to have such customization.

**Comment by boutell** [comment]
Why is it required? What does it accomplish? It would help if I could see a
situation where this matters.

On Thu, May 21, 2015 at 7:13 AM, Pavlo Yuriychuk <notifications@github.com>
wrote:

> @boutell <https://github.com/boutell> : I wanted to do that just to do
> more advanced handling of Html text inside links. It is required in our
> project to escape almost all special characters. You may treat this feature
> as just nice to have, but IMHO it is essential to have such customization.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/48#issuecomment-104232487>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
Actually though, in fairness: I did accept the textFilter option as a pull request. And this is in a similar spirit.

So, if you want to submit a pull request for an escapeEntities option, I am open to accepting that.

**Comment by pavlo-yuriychuk** [comment]
@boutell : If is possible to override standard `escapeHtmlEntities` than it is more than enough. The situation is the following one: you need to remove all `<a>` tags including link text.

**Comment by boutell** [comment]
Then this has nothing to do with escaping, you want to eliminate the text
entirely for a specific tag. The escape function has no idea what the tag
is.

Check out this code in index.js:

var nonTextTagsMap = {
    script: true,
    style: true
  };

All you need to do is write a pull request to add an option which makes it
straightforward to add tags to this list. Something like a nonTextTags
option which takes an array of tag names, and populates the above object,
defaulting to [ 'script', 'style' ].



On Thu, May 21, 2015 at 9:18 AM, Pavlo Yuriychuk <notifications@github.com>
wrote:

> @boutell <https://github.com/boutell> : If is possible to override
> standard escapeHtmlEntities than it is more than enough. The situation is
> the following one: you need to remove all <a> tags including link text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/48#issuecomment-104275074>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by pavlo-yuriychuk** [comment]
@boutell : Ah, sorry. Ok I will close this request and make another workaround.

**Comment by boutell** [comment]
No worries.

On Thu, May 21, 2015 at 9:24 AM, Pavlo Yuriychuk <notifications@github.com>
wrote:

> @boutell <https://github.com/boutell> : Ah, sorry. Ok I will close this
> request and make another workaround.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/48#issuecomment-104276663>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
