### ISSUE TITLE
Remove paragraphs without text except if there's an image inside

### ISSUE THREAD

**Issue by tommedema** [punkave/sanitize-html#58]
I'm trying to remove all `p`s without text content, except when there's an `img` tag inside or in any of its children.

Currently I have this:

             exclusiveFilter: function(frame) {

		           var contentTags = ['p'];
 
                           //disallow empty anchors, divs or paragraphs
		            if (contentTags.indexOf(frame.tag) !== -1 && !frame.text.trim())
		            {
		            	return true;
		            }

		            return false;
		        }

Unfortunately I can't seem to get the inner HTML of the frame, like `frame.html` (or better yet a parsed object for easier searching), to check if there is an image inside.

Is this correct? Is there any way to achieve my goal?

**Comment by boutell** [comment]
This kind of thing might be better suited to the cheerio module.

On Sat, Jul 4, 2015 at 10:19 AM, tommedema <notifications@github.com> wrote:

> I'm trying to remove all ps without text content, except when there's an
> img tag inside or in any of its children.
>
> Currently I have this:
>
>                     exclusiveFilter: function(frame) {
>
>                var contentTags = ['p'];
>
>                        //disallow empty anchors, divs or paragraphs
>                 if (contentTags.indexOf(frame.tag) !== -1 && !frame.text.trim())
>                 {
>                     return true;
>                 }
>
>                 return false;
>             }
>
> Unfortunately I can't seem to get the inner HTML of the frame, like
> frame.html (or better yet a parsed object for easier searching), to check
> if there is an image inside.
>
> Is this correct? Is there any way to achieve my goal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/58>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by maddy2894** [comment]
Hi @tommedema @boutell, is there any solution for this? 
I have similar kind of requirement, need to sanitize or not allow <img> inside of <a href>

eg:
<a href="somelink"> <img> </a>
in this either <a> should be removed or <img> tag should not be allowed. 
Thanks in Advance

**Comment by boutell** [comment]
For more complex manipulations like this you should use the `cheerio` module which is designed to let you do whatever jQuery can do in terms of finding things quickly with selectors and mopping them up. This module is for simple sanitization tasks.
