### ISSUE TITLE
Change relative URLs to absolute URLs

### ISSUE THREAD

**Issue by tommedema** [punkave/sanitize-html#59]
I've got a string of HTML and the URL from which the HTML originates. E.g. the URL can be "http://domain.com/sub/page.html" and the URL could be `<img src="../img/1.jpg">`.

Now, I would like to enter the origin URL and then transform the HTML to absolute URLs, so the result should become `<img src="http://domain.com/img/1.jpg">`.

What would be the most straightforward way to achieve this?

**Comment by tommedema** [comment]
FYI I achieved this using https://www.npmjs.com/package/rel-to-abs

**Comment by boutell** [comment]
Also my absolution module

**Comment by boutell** [comment]
Closing this as there's a separate module for it.
