### ISSUE TITLE
Removing redundant tags

### ISSUE THREAD

**Issue by tommedema** [punkave/sanitize-html#61]
After cleaning I end up with a lot of redundant tags. E.g. the sanitized html might look like:

           <div>
                <div>
                    <span>
                        <span>
                            <a href="http://app.meihua.info" target="_blank">客户端</a>
                        </span>
                    </span>
                </div>
            </div>

Ideally this would be sanitized to:

            <div>
                  <a href="http://app.meihua.info" target="_blank">客户端</a>
            </div>

I understand that you would like to keep these kind of complex mutations outside of this project, and I'd be happy to implement a solution using cheerio or similar. However, isn't this a clear case of sanitization -- since the prior HTML contains a lot of redundant tags?

Regardless, does anyone have a suggestion on what kind of mutations I would have to do using something like cheerio to achieve such kind of cleanup?

**Comment by boutell** [comment]
Whether this is redundant is entirely in the eye of the beholder. More
importantly though, the parser can't tell if a tag is redundant without
"looking ahead." That is, if three div's are opened in succession, that's
not redundant unless they are also closed in succession. Until they are
closed we can't tell if they have distinct content. And that would mean
buffering everything up, which so far we've avoided in this design.

On Tue, Jul 14, 2015 at 10:15 PM, tommedema <notifications@github.com>
wrote:

> After cleaning I end up with a lot of redundant tags. E.g. the sanitized
> html might look like:
>
>        <div>
>             <div>
>                 <span>
>                     <span>
>                         <a href="http://app.meihua.info" target="_blank">客户端</a>
>                     </span>
>                 </span>
>             </div>
>         </div>
>
> Ideally this would be sanitized to:
>
>         <div>
>               <a href="http://app.meihua.info" target="_blank">客户端</a>
>         </div>
>
> I understand that you would like to keep these kind of complex mutations
> outside of this project, and I'd be happy to implement a solution using
> cheerio or similar. However, isn't this a clear case of sanitization --
> since the prior HTML contains a lot of redundant tags?
>
> Regardless, does anyone have a suggestion on what kind of mutations I
> would have to do using something like cheerio to achieve such kind of
> cleanup?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/61>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by tommedema** [comment]
That's a good reason for leaving this to another library. I am not sure what to call it though, `postsanitize-html`? ;-)
