### ISSUE TITLE
Markdown quote tag escaped

### ISSUE THREAD

**Issue by tgienger** [punkave/sanitize-html#62]
Is there a way to allow the greater than  '>' symbol for quotes in markdown?

**Comment by boutell** [comment]
This is invalid HTML, so no... I think it would make sense to write a separate sanitize-markdown module.

**Comment by jcalfee** [comment]
We did an update .. please try again.

**Comment by boutell** [comment]
Please try what again?

**Comment by jcalfee** [comment]
Sorry, I miss-read the ticket.  It got this link at the same time we had a blockquote rendering issue.
