### ISSUE TITLE
iframe sanitizing redirects to "data:,"

### ISSUE THREAD

**Issue by romainmougel** [punkave/sanitize-html#71]
In my app, the user submits a string client-side to be cleaned server-side. If there is no iframe, everything is okay and the user is redirected to a page displaying the cleaned string.

I have the following configuration regarding iframe :
allowedAttributes: {
   iframe:['src','width','height','frameborder','webkitallowfullscreen','mozallowfullscreen','allowfullscreen','allowtransparency','scrolling','class']
}

If the strings contains a iframe, the user is not redirected on the wanted page, but to this strange url : 
data:,

Any idea?

**Comment by boutell** [comment]
I'll need a specific example- pass this string in, get this unexpected
string out.

**Comment by romainmougel** [comment]
The out string is correct :

<iframe src="//www.lemonde.fr/"></iframe> returns <iframe src="//www.lemonde.fr/"></iframe>

But the redirection bugs only if there is a iframe.
Do you think it means the problem is somewhere in my app instead? Sorry if it is the case, I'm just lost here.

**Comment by boutell** [comment]
sanitize-html is a module that takes input HTML, applies some sanitization
rules, and outputs HTML that confirms to those rules. That's it (:

So if it's not doing that... you open an issue here.

But if it is... the question doesn't really belong here.

(I'd try to help, but given the lack of a clear-cut example with sample
data, I really can't guess why your iframe isn't iframing.)


On Tue, Aug 18, 2015 at 10:03 AM, romainmougel <notifications@github.com>
wrote:

> The out string is correct :
> returns
>
> But the redirection bugs only if there is a iframe.
> Do you think it means the problem is somewhere in my app instead? Sorry if
> it is the case, I'm just lost here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/71#issuecomment-132219353>
> .
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by romainmougel** [comment]
Ok sorry I disturbed you! Thx anyway. Great module by the way :)
