### ISSUE TITLE
Always returns a non-empty string, even "undefined" or "false"

### ISSUE THREAD

**Issue by franciscop** [punkave/sanitize-html#81]
For debugging purposes I arrived to this test-case:

```js
console.log("Undefined", sanitize(), typeof sanitize());
console.log("Empty", sanitize(''), typeof sanitize(''));
console.log("False", sanitize(false), typeof sanitize(false));
```

Gives an unexpected output (note the *string* at the end):

```js
Undefined undefined string
Empty  string
False false string
```

So basically if nothing is passed, it will return an string that says "undefined" which is really odd (and was a weird bug to debug). Therefore it'll pass all successive tests to check the html, since there *will be* a non-empty string. For example, in jade for a "sanitized" html:

```jade
// Always returns true (not expected)
if !html
if (typeof html !== "undefined")
if (html.length > 0)
// ... at this point I was wondering, since jade's output displayed "undefined"

// Just for the kicks, this misteriously worked:
if (html === "undefined")
```

So as you can see, it is a really weird output when a non-valid string is set as input.

## Proposed solution

For the same case as before, you could return some of these "more sensible" outputs:

1. false
2. ""
3. undefined
4. throw Error

I think all of them are better than the current usage, but I highly recommend either 1. or 2. which are both *falsy*.

## Temporary solution

This works so far for my purposes (and might be useful for someone else):

```js
html = html ? sanitize(html, sanitizeOpt) : false;
```

**Comment by franciscop** [comment]
I don't have deep knowledge of the code, but from a quick glance I'd say you can just do this:

```js

function sanitizeHtml(html, options, _recursing) {

  if (!html) return html; // Just return it if falsy

  var result = '';

  function Frame(tag, attribs) {
    var that = this;
    this.tag = tag;
    this.attribs = attribs || {};
    this.tagPosition = result.length;
    this.text = ''; // Node inner text

    this.updateParentNodeText = function() {
      if (stack.length) {
          var parentFrame = stack[stack.length - 1];
          parentFrame.text += that.text;
      }
    };
  }

```

**Comment by boutell** [comment]
After giving this some thought, I have decided it is not this module's responsibility to check whether you passed it an argument that is actually a string.
