### ISSUE TITLE
Unconfigurable escaping of & < > "

### ISSUE THREAD

**Issue by algebris** [punkave/sanitize-html#87]
After passing my text through sanitizeHtml() I'm getting escaped characters & < > " by default.
Is it possible to turn it off? 
PS:
I found function escapeHtml() doing that
and parameter decodeEntities: [boolean] – I didn't found any use of it ...

**Comment by boutell** [comment]
It is never incorrect to escape these characters at all times in HTML if
they don't have their special meanings in HTML (if they are not being used
to open and close tags or specify escape sequences). An option not to do
this would open the door to possible attack vectors.

On Sun, Jan 24, 2016 at 12:08 PM, Vyacheslav Frolov <
notifications@github.com> wrote:

> After passing my text through sanitizeHtml() I'm getting escaped
> characters & < > " by default
> Is it possible to turn it off?
> I found function escapeHtml() doing that
> and parameter decodeEntities: [boolean] – I didn't found any use of it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/87>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by rafael-paiva** [comment]
I'd love if `decodeEntities` worked ☹️
