### ISSUE TITLE
Incorrectly does not allow `<3`.

### ISSUE THREAD

**Issue by Morgul** [punkave/sanitize-html#88]
I'm working on a chat app, and it looks like `<3` is getting stripped. It counts as a broken tag, near as I can tell.

**Comment by boutell** [comment]
It is a broken tag. If you want your HTML to pass validation, escape < >
and & correctly.

On Sun, Feb 7, 2016 at 12:27 AM, Christopher S. Case <
notifications@github.com> wrote:

> I'm working on a chat app, and it looks like <3 is getting stripped. It
> counts as a broken tag, near as I can tell.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/issues/88>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
That is, use &lt; &gt; &amp;

(If you want to let the public type "bogo-HTML" that isn't really quite HTML, it's your responsibility to make it valid-ish HTML before it reaches sanitize-html.)

**Comment by boutell** [comment]
(I edited my comment to show the escape codes correctly.)
