### ISSUE TITLE
What are the core differences with tidyhtml?

### ISSUE THREAD

**Issue by eightyfive** [punkave/sanitize-html#92]
Hi,

Thanks for this package, it saved me a lot of precious time.

I was wondering though, could you highlight the core differences with tidyhtml library:
https://github.com/vavere/htmltidy
https://github.com/lovasoa/tidy-html5

(by the way, quick note, the html**5** version worked much better for my use case)

Also, can you confirm that text content in never lost with `sanitize-html`?

Thanks in advance.

**Comment by boutell** [comment]
I'm not really an expert on tidyhtml, not having used it. The lack of documentation for the node wrapper for tidyhtml limits me in how much I can really comment. tidyhtml itself is probably a lot more capable, if you need those capabilities, you might want to use it.

However, sanitize-html is a pretty thin wrapper around htmlparser2. It's pure javascript. Whereas the node wrapper for tidyhtml actually spawns a new process for every document to be tidied. The overhead of that is probably great enough to say that sanitize-html would be a lot faster except perhaps in pathological cases (gigantic documents).

And of course as a pure javascript solution sanitize-html will work on platforms the tidyhtml wrapper has no binaries for.

**Comment by eightyfive** [comment]
Thanks.

For the record I used a combination of both tools cause tidyhtml had a feature I couldn't find in sanitize-html:
"De-dup/merge nodes: <span><span style="some"><spa... --> <span style="some">"

With sanitize-html I could only filter them out, not de-dup.

**Comment by eightyfive** [comment]
Replying to my own last question:
> Also, can you confirm that text content in never lost with sanitize-html?

Right in the docs!
> Normally, with a few exceptions, if a tag is not allowed, **all of the text within it is preserved**, and so are any allowed tags within it.

https://github.com/punkave/sanitize-html#discarding-the-entire-contents-of-a-disallowed-tag
