### ISSUE TITLE
How to allow '&' and not convert it to '&amp;'?

### ISSUE THREAD

**Issue by tarunjadhwani** [punkave/sanitize-html#94]
Is there a way to allow a special character like '&' and not escape it to '&amp;' ?

**Comment by boutell** [comment]
This is incorrect HTML and will not be added.

**Comment by eddieajau** [comment]
@boutell 

>This is incorrect HTML and will not be added.

This is true, but my use-case is that I'm sanitising before saving to the database. In that case, it's perfectly valid to allow `&`.

**Comment by boutell** [comment]
I don't know exactly what you mean by that, but sanitize-html sanitizes things as valid HTML, and so it is out of scope for it to accept something that isn't.
