### ISSUE TITLE
I need to 'style' attribute

### ISSUE THREAD

**Issue by yahao87** [punkave/sanitize-html#97]
I need to under the state
<span style="background-color: rgb(255, 255, 0);">dsf</span>

I used wyswyg editor summernote. (http://summernote.org/)

sanitizeHtml(html,
		{
			allowedTags: [ 'h3', 'h4', 'h5', 'h6', 'blockquote', 'p', 'a', 'ul', 'ol',
				'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'code', 'hr', 'br', 'div',
				'table', 'thead', 'caption', 'tbody', 'tr', 'th', 'td', 'pre',
				'item-block', 'iframe', 'img' ],
			allowedAttributes: {
				"*":['style', 'class'],
......
...
...
transformTags: {
				'span': function(tagName, attribs) {
						return {
							tagName: tagName,
							attribs: attribs
						};
					}
				},

But all it cleared.
**style is removed all.**

How do I use it?

**Comment by boutell** [comment]
There is a unit test showing this works, and I wrote another just to check. If you suspect otherwise please submit a pull request with a failing unit test.

**Comment by yahao87** [comment]
I do not speak English well.
The code was cut above.

In short

![image](https://cloud.githubusercontent.com/assets/10890178/13912034/ebd7a698-ef7b-11e5-972e-94043f3db7db.png)


![image](https://cloud.githubusercontent.com/assets/10890178/13912039/f8f51572-ef7b-11e5-89b0-753eee7847d9.png)


sanitizeHtml(html,
{
allowedTags: [ 'h3', 'h4', 'h5', 'h6', 'blockquote', 'p', 'a', 'ul', 'ol',
'nl', 'li', 'b', 'i', 'strong', 'em', 'strike', 'code', 'hr', 'br', 'div',
'table', 'thead', 'caption', 'tbody', 'tr', 'th', 'td', 'pre',
'item-block', 'iframe', 'img' ],
allowedAttributes: {
"*":['style', 'class'],

result is 
![image](https://cloud.githubusercontent.com/assets/10890178/13912056/2bd95bec-ef7c-11e5-9c87-9227e6e7ec04.png)


I'm not there to apply some style?

**Comment by boutell** [comment]
Please paste the complete test program that fails, rather than screenshots and partial code. Thanks!

**Comment by simison** [comment]
@yahao87 you can wrap code examples with ``` signs, see https://guides.github.com/features/mastering-markdown/ for details.

**Comment by yahao87** [comment]
thx everybody ^^
It was my mistake.
I did not put span in the 'allowedTags'.

i'm sorry
:)
